(let ()
  (import expression-editor)
  (ee-history-limit 500)
  (ee-bind-key "^p" (ee-compose ee-history-bwd-prefix ee-end-of-entry))
  (ee-bind-key "^n" (ee-compose ee-history-fwd-prefix ee-end-of-entry))
  (ee-bind-key "^d" (ee-compose ee-eof ee-accept))
  (ee-bind-key "^f" ee-indent)
  (ee-bind-key "^u" (ee-compose ee-set-mark ee-beginning-of-line ee-delete-between-point-and-mark))
  (ee-bind-key "^w" (ee-compose ee-set-mark ee-backward-word ee-delete-between-point-and-mark)))
