#!/bin/sh
[ -x /usr/bin/file -a -x /usr/bin/iconv ] || exit 1
case $(/usr/bin/file -b "$1") in
*UTF-16*) conv=UTF-16;;
*UTF-32*) conv=UTF-32;;
Non-ISO\ extended-ASCII\ text*) conv=CP932;;
*) exit 1;;
esac
env=${LANG#*.}
/usr/bin/iconv -f $conv -t ${env:-UTF-8} "$1"
