if has('linux')
	set guifont=Monospace\ 12
elseif has('win32')
	set guifont=Consolas:h11
	let s:gvim_win_pos_file = expand('~/.gvimwinpos')
	function! s:save_gvim_win_pos()
		let s:options = [getwinposx(), getwinposy()]
		call writefile(s:options, s:gvim_win_pos_file)
	endfunction
	augroup SaveGvimWinPos
		autocmd!
		autocmd VimLeavePre * call <SID>save_gvim_win_pos()
	augroup END
	if filereadable(s:gvim_win_pos_file)
		let s:opt = readfile(s:gvim_win_pos_file)
		let s:n = str2nr(strpart(v:servername, 4))
		execute 'winpos ' . (s:opt[0] + 32 * s:n) . ' ' . (s:opt[1] + 32 * s:n)
	endif
	nnoremap <silent> <M-Space> :simalt ~<CR>
endif
set guioptions=!Mr
set lines=30 columns=86
