nmap <buffer> gu <Plug>(InfoUp)
nmap <buffer> gn <Plug>(InfoNext)
nmap <buffer> gp <Plug>(InfoPrev)
nmap <buffer> gm <Plug>(InfoMenu)
nmap <buffer> gf <Plug>(InfoFollow)
nmap <buffer> go <Plug>(InfoGoto)
