vimfx.set('mode.normal.esc', '<force><escape> <force><c-[>')
vimfx.set('mode.normal.find', 'a/')
vimfx.set('mode.normal.find_highlight_all', '/')
vimfx.set('mode.normal.history_back', 'J')
vimfx.set('mode.normal.history_forward', 'K')
vimfx.set('mode.normal.history_list', 'gJ')
vimfx.set('mode.normal.scroll_page_up', '<s-space> b')
vimfx.set('mode.normal.tab_move_backward', 'gH')
vimfx.set('mode.normal.tab_move_forward', 'gL')
vimfx.set('mode.normal.tab_select_next', 'L gt')
vimfx.set('mode.normal.tab_select_oldest_unvisited', 'gk')
vimfx.set('mode.normal.tab_select_previous', 'H gT')
vimfx.set('next_patterns', 'next  ›  »  ▶  →  >>  >  more  older  次のページ  次のページへ  次へ')
vimfx.set('prev_patterns', 'prev  previous  ‹  «  ◀  ←  <<  <  back  newer  前のページ  前のページへ  前へ')
vimfx.set('prevent_autofocus', true)
