#!/usr/bin/perl
$latex		= 'uplatex -kanji=utf8 -synctex=1 -halt-on-error';
$bibtex		= 'upbibtex';
$biber		= 'biber -u -U --output_safechars';
$dvipdf		= 'dvipdfmx %O -o %D %S';
$makeindex	= 'upmendex %O -o %D %S';
$max_repeat	= 5;
$pdf_mode	= 3;
$pvc_view_file_via_temporary = 0;
if ($^O eq 'darwin') {
	$pdf_previewer = 'open';
} elsif ($^O eq 'linux') {
	$pdf_previewer = 'xdg-open';
}
